# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: http
      protocol: TCP
      port: 80
      #   nodePort: 30130
      targetPort: 9090
---

# DEPOLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  #  minReadySeconds: 20
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: heavyflood/api-test:release
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9090
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command: ["sh", "-c", "cd /"]
            initialDelaySeconds: 30
            periodSeconds: 30
          #          timeoutSeconds: 1
          #          successThreshold: 1
          #          failureThreshold: 3
          #          httpGet:
          #            path: /
          #            port: 8080
          #          tcpSocket:
          #            port: 8080
          #          initialDelaySeconds: 5
          #          periodSeconds: 5
          #          successThreshold: 1
          readinessProbe:
            exec:
              command: ["sh", "-c", "cd /"]
            initialDelaySeconds: 30
            periodSeconds: 15
          #          timeoutSeconds: 1
          #          successThreshold: 1
          #          failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 20"]
      imagePullSecrets:
        - name: regcred
---

#Ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: app-ip
  labels:
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: app
              servicePort: 9090